name: kvlm
services:
  database:
    container_name: database
    image: postgis/postgis:17-master
    platform: linux/amd64
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    healthcheck:
      test:
        [
          'CMD',
          'pg_isready',
          '-U',
          '${DB_USER}',
          '-d',
          '${DB_DATABASE}',
          '-h',
          'localhost',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s

  cache:
    container_name: cache
    image: redis:6
    healthcheck:
      test: ['CMD-SHELL', "[ $$(redis-cli ping) = 'PONG' ]"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s

  proxy:
    container_name: proxy
    image: traefik:v3.5
    command:
      - --api.basePath=/proxy
      - --api.dashboard=true
      - --log.level=DEBUG
      - --providers.docker
      - --providers.docker.exposedByDefault=false
      - --entryPoints.web.address=:80
      - --entryPoints.web.asDefault=true
    ports:
      - '${TRAEFIK_HTTP_PORT:-80}:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.proxy.rule=Host(`kvlm.local`) && PathPrefix(`/proxy`)
      - traefik.http.routers.proxy.service=api@internal
      # - traefik.http.routers.proxy.middlewares=proxy
      # - traefik.http.middlewares.proxy.basicauth.users=dgfggadmin:$apr1$7HkZqKZK$Idl9VnMOmY3lS1f7LoXfi0

  cms:
    container_name: cms
    image: directus/directus:11.10.2
    labels:
      - traefik.enable=true
      - traefik.http.routers.cms.rule=Host(`kvlm.local`) && PathPrefix(`/cms`)
      - traefik.http.routers.cms.entrypoints=web
      - traefik.http.routers.cms.service=cms-kvlm
      - traefik.http.routers.cms.middlewares=redirect-admin-prefix,strip-cms-prefix
      - traefik.http.middlewares.redirect-admin-prefix.redirectregex.regex=^${APP_HOST}/cms/?$
      - traefik.http.middlewares.redirect-admin-prefix.redirectregex.replacement=${APP_HOST}/cms/admin
      - traefik.http.middlewares.redirect-admin-prefix.redirectregex.permanent=true
      - traefik.http.middlewares.strip-cms-prefix.stripprefix.prefixes=/cms
    volumes:
      - cms-uploads:/directus/uploads
      - cms-extensions:/directus/extensions
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
    environment:
      SECRET: ${DIRECTUS_SECRET}

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      CACHE_ENABLED: ${CACHE_ENABLED}
      CACHE_AUTO_PURGE: ${CACHE_AUTO_PURGE}
      CACHE_STORE: 'redis'
      REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      WEBSOCKETS_ENABLED: ${WEBSOCKETS_ENABLED}

      PUBLIC_URL: ${PUBLIC_URL}

      CORS_ENABLED: ${CORS_ENABLED}
      CORS_ORIGIN: ${CORS_ORIGIN}

      REFRESH_TOKEN_COOKIE_SECURE: ${REFRESH_TOKEN_COOKIE_SECURE}
      REFRESH_TOKEN_COOKIE_SAME_SITE: ${REFRESH_TOKEN_COOKIE_SAME_SITE}
      REFRESH_TOKEN_DOMAIN: ${REFRESH_TOKEN_COOKIE_DOMAIN}

      SESSION_COOKIE_SECURE: ${SESSION_COOKIE_SECURE}
      SESSION_COOKIE_SAME_SITE: ${SESSION_COOKIE_SAME_SITE}
      SESSION_COOKIE_DOMAIN: ${SESSION_COOKIE_DOMAIN}

      EXTENSIONS_PATH: ${EXTENSIONS_PATH}
      EXTENSIONS_AUTO_RELOAD: ${EXTENSIONS_AUTO_RELOAD}

      CONTENT_SECURITY_POLICY_DIRECTIVES__FRAME_SRC: ${CONTENT_SECURITY_POLICY_DIRECTIVES__FRAME_SRC}

      EMAIL_TRANSPORT: ${EMAIL_TRANSPORT}
      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST}
      EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT}
      EMAIL_SMTP_USER: ${EMAIL_SMTP_USER}
      EMAIL_SMTP_PASSWORD: ${EMAIL_SMTP_PASSWORD}

  demo:
    container_name: demo
    build:
      context: .
      target: demo
    image: kvlm/demo
    labels:
      - traefik.enable=true
      - traefik.http.routers.demo.rule=Host(`kvlm.local`) && PathPrefix(`/demo`)
      - traefik.http.routers.demo.entrypoints=web
      - traefik.http.routers.demo.service=demo-kvlm

  website:
    container_name: website
    build:
      context: .
      target: website
      args:
        - NODE_VERSION=${NODE_VERSION}
    image: kvlm/website
    labels:
      - traefik.enable=true
      - traefik.http.routers.website.rule=Host(`kvlm.local`) && PathPrefix(`/`)
      - traefik.http.routers.website.entrypoints=web
      - traefik.http.routers.website.service=website-kvlm

volumes:
  cms-uploads:
    name: kvlm.cms.uploads
  cms-extensions:
    name: kvlm.cms.extensions
  database-data:
    name: kvlm.database.data
