packages:
  - packages/ui
  - packages/website

minimumReleaseAgeExclude:
  - "@enke.dev/lint@0.13.9"
  - "@enke.dev/lit-utils@0.4.7"
  - "@html-eslint/core@0.65.0"
  - "@html-eslint/eslint-plugin@0.65.0"
  - "@html-eslint/parser@0.65.0"
  - "@html-eslint/template-parser@0.65.0"
  - "@html-eslint/template-syntax-parser@0.65.0"
  - "@html-eslint/types@0.65.0"
  - '@enke.dev/logbox@0.0.3'
