packages:
  - packages/ui
  - packages/website
  - packages/website.bkp

injectWorkspacePackages: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - rs-module-lexer
  - sharp
  - unrs-resolver

syncInjectedDepsAfterScripts:
  - build
