packages:
  - packages/ui
  - packages/website

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - sharp
  - unrs-resolver

syncInjectedDepsAfterScripts:
- build
injectWorkspacePackages: true
