packages:
  - packages/ui
  - packages/website

injectWorkspacePackages: true

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - esbuild
  - rs-module-lexer
  - sharp
  - unrs-resolver

syncInjectedDepsAfterScripts:
  - build
