packages:
  - packages/ui
  - packages/website
  - packages/website.bkp

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - sharp
  - unrs-resolver

syncInjectedDepsAfterScripts:
  - build
injectWorkspacePackages: true
