/**
 * Bakes the terrain of the `kvlm-houses` scene: cuts the ground to the seam
 * once, here, and writes what comes out as positions and indices. Cutting it
 * takes longer than the rest of the scene together, and it only changes when
 * the model does. The colours are not baked - the palette lays them on.
 *
 * Run with `npm run data:terrain` after changing anything the seam is built
 * from. The test suite says when it is stale.
 *
 * Run under node rather than bun: the browser the scene runs in shares node's
 * engine, and with it the last digit of every sine the rings are laid out by.
 */

import { writeFile } from 'node:fs/promises';

import { buildTerrain } from '../src/models/terrain/terrain.js';

const OUTPUT = new URL('../src/data/terrain.baked.ts', import.meta.url);

const started = performance.now();
const { positions, indices } = buildTerrain();
const vertices = positions.length / 3;

// the same packing the scene unpacks: the indices as small as the vertices allow
const packed = (array: ArrayBufferView) =>
  Buffer.from(array.buffer, array.byteOffset, array.byteLength).toString('base64');
const index = vertices > 0xffff ? new Uint32Array(indices) : new Uint16Array(indices);

const contents = `// Generated by scripts/bake-terrain.ts - do not edit by hand.
//
// The terrain cut to the seam: ${vertices} vertices, ${indices.length / 3} faces.
// Positions as little endian float32 x, y, z; indices as ${index.BYTES_PER_ELEMENT * 8} bit integers.

export const GROUND = {
  positions:
    '${packed(new Float32Array(positions))}',
  indices:
    '${packed(index)}',
};
`;

await writeFile(OUTPUT, contents);
console.log(
  `baked ${vertices} vertices, ${indices.length / 3} faces in ${Math.round(performance.now() - started)}ms`
);
