"""
Bake the Saab for the scene: the model built by saab.py, its faces sorted into
materials by saab_materials.py, reduced by saab_reduce.py, and written as one
list of positions and indices per material - in the scene's own axes and in
meters: nose to +x, the middle at the origin, the wheels on y = 0, up on y, the
car's side on z. The palette lays the colours on.

    python saab_bake.py saab.stl ../src/data/saab.baked.ts
"""

import base64
import sys

import numpy as np
import trimesh

from saab_materials import MATERIALS, classify, split_for_materials
from saab_reduce import reduce_mesh


def packed(array):
    return base64.b64encode(array.tobytes()).decode()


def main(source, target):
    mesh = trimesh.load(source)
    mesh.merge_vertices()
    classified = split_for_materials(mesh)
    ids = classify(classified)
    reduced, ids = reduce_mesh(classified, ids)
    # the model's axes (x nose, y across, z up, mm) into the scene's (x nose, y up, z across, m)
    points = np.stack([reduced.vertices[:, 0], reduced.vertices[:, 2], -reduced.vertices[:, 1]], axis=1) / 1000.0
    faces = reduced.faces  # the axes swap is a pure rotation, the winding stays
    parts, total = [], 0
    for index, name in enumerate(MATERIALS):
        picked = faces[ids == index]
        if not len(picked):
            continue
        used = np.unique(picked)
        remap = np.zeros(len(points), np.int64)
        remap[used] = np.arange(len(used))
        positions = points[used].astype(np.float32)
        indices = remap[picked].astype(np.uint16)
        total += len(picked)
        parts.append(
            f"  {name}: {{\n    positions:\n      '{packed(positions)}',\n    indices:\n      '{packed(indices.reshape(-1))}',\n  }},"
        )
    contents = (
        "// Generated by scripts/saab_bake.py - do not edit by hand.\n//\n"
        f"// The Saab 900: {total} faces in {len(parts)} materials, as little endian float32 x, y, z\n"
        "// in meters (nose to +x, middle at the origin, wheels on y = 0) and 16 bit indices.\n\n"
        "export const SAAB_BAKED = {\n" + "\n".join(parts) + "\n} as const;\n"
    )
    with open(target, "w") as out:
        out.write(contents)
    print(f"{total} faces, {len(contents) // 1024} KB")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
