/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface KvlmRoot {
    }
    interface KvlmTerrain {
    }
}
declare global {
    interface HTMLKvlmRootElement extends Components.KvlmRoot, HTMLStencilElement {
    }
    var HTMLKvlmRootElement: {
        prototype: HTMLKvlmRootElement;
        new (): HTMLKvlmRootElement;
    };
    interface HTMLKvlmTerrainElement extends Components.KvlmTerrain, HTMLStencilElement {
    }
    var HTMLKvlmTerrainElement: {
        prototype: HTMLKvlmTerrainElement;
        new (): HTMLKvlmTerrainElement;
    };
    interface HTMLElementTagNameMap {
        "kvlm-root": HTMLKvlmRootElement;
        "kvlm-terrain": HTMLKvlmTerrainElement;
    }
}
declare namespace LocalJSX {
    interface KvlmRoot {
    }
    interface KvlmTerrain {
    }
    interface IntrinsicElements {
        "kvlm-root": KvlmRoot;
        "kvlm-terrain": KvlmTerrain;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "kvlm-root": LocalJSX.KvlmRoot & JSXBase.HTMLAttributes<HTMLKvlmRootElement>;
            "kvlm-terrain": LocalJSX.KvlmTerrain & JSXBase.HTMLAttributes<HTMLKvlmTerrainElement>;
        }
    }
}
