/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { GenericRouteContext } from "./utils/router.utils.js";
export { GenericRouteContext } from "./utils/router.utils.js";
export namespace Components {
    interface KvlmAuthenticate {
        "at": string;
    }
    interface KvlmBackground {
        "image": string;
        "preview": string;
    }
    interface KvlmButton {
        "block": boolean;
        "disabled": boolean;
        "download"?: string;
        "forzeBlock"?: boolean;
        "href"?: string;
        "target"?: string;
        "type": HTMLButtonElement['type'];
    }
    interface KvlmButtons {
        "direction": 'horizontal' | 'vertical';
        "forzeDirection"?: 'horizontal' | 'vertical';
    }
    interface KvlmCalendar {
    }
    interface KvlmContent {
        "visible": boolean;
    }
    interface KvlmFooter {
    }
    interface KvlmGenericPage {
        "context": GenericRouteContext;
        "src": string;
    }
    interface KvlmHeader {
    }
    interface KvlmIcon {
    }
    interface KvlmIconLogo {
    }
    interface KvlmLoader {
    }
    interface KvlmMain {
    }
    interface KvlmNewsletterRegistration {
        "at": string;
    }
    interface KvlmRoot {
    }
    interface KvlmSubpages {
        "src": string;
    }
    interface KvlmToday {
    }
    interface KvlmUpcomingEvents {
        "calendarUrl": string;
        "loading"?: string;
    }
}
export interface KvlmBackgroundCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLKvlmBackgroundElement;
}
declare global {
    interface HTMLKvlmAuthenticateElement extends Components.KvlmAuthenticate, HTMLStencilElement {
    }
    var HTMLKvlmAuthenticateElement: {
        prototype: HTMLKvlmAuthenticateElement;
        new (): HTMLKvlmAuthenticateElement;
    };
    interface HTMLKvlmBackgroundElement extends Components.KvlmBackground, HTMLStencilElement {
    }
    var HTMLKvlmBackgroundElement: {
        prototype: HTMLKvlmBackgroundElement;
        new (): HTMLKvlmBackgroundElement;
    };
    interface HTMLKvlmButtonElement extends Components.KvlmButton, HTMLStencilElement {
    }
    var HTMLKvlmButtonElement: {
        prototype: HTMLKvlmButtonElement;
        new (): HTMLKvlmButtonElement;
    };
    interface HTMLKvlmButtonsElement extends Components.KvlmButtons, HTMLStencilElement {
    }
    var HTMLKvlmButtonsElement: {
        prototype: HTMLKvlmButtonsElement;
        new (): HTMLKvlmButtonsElement;
    };
    interface HTMLKvlmCalendarElement extends Components.KvlmCalendar, HTMLStencilElement {
    }
    var HTMLKvlmCalendarElement: {
        prototype: HTMLKvlmCalendarElement;
        new (): HTMLKvlmCalendarElement;
    };
    interface HTMLKvlmContentElement extends Components.KvlmContent, HTMLStencilElement {
    }
    var HTMLKvlmContentElement: {
        prototype: HTMLKvlmContentElement;
        new (): HTMLKvlmContentElement;
    };
    interface HTMLKvlmFooterElement extends Components.KvlmFooter, HTMLStencilElement {
    }
    var HTMLKvlmFooterElement: {
        prototype: HTMLKvlmFooterElement;
        new (): HTMLKvlmFooterElement;
    };
    interface HTMLKvlmGenericPageElement extends Components.KvlmGenericPage, HTMLStencilElement {
    }
    var HTMLKvlmGenericPageElement: {
        prototype: HTMLKvlmGenericPageElement;
        new (): HTMLKvlmGenericPageElement;
    };
    interface HTMLKvlmHeaderElement extends Components.KvlmHeader, HTMLStencilElement {
    }
    var HTMLKvlmHeaderElement: {
        prototype: HTMLKvlmHeaderElement;
        new (): HTMLKvlmHeaderElement;
    };
    interface HTMLKvlmIconElement extends Components.KvlmIcon, HTMLStencilElement {
    }
    var HTMLKvlmIconElement: {
        prototype: HTMLKvlmIconElement;
        new (): HTMLKvlmIconElement;
    };
    interface HTMLKvlmIconLogoElement extends Components.KvlmIconLogo, HTMLStencilElement {
    }
    var HTMLKvlmIconLogoElement: {
        prototype: HTMLKvlmIconLogoElement;
        new (): HTMLKvlmIconLogoElement;
    };
    interface HTMLKvlmLoaderElement extends Components.KvlmLoader, HTMLStencilElement {
    }
    var HTMLKvlmLoaderElement: {
        prototype: HTMLKvlmLoaderElement;
        new (): HTMLKvlmLoaderElement;
    };
    interface HTMLKvlmMainElement extends Components.KvlmMain, HTMLStencilElement {
    }
    var HTMLKvlmMainElement: {
        prototype: HTMLKvlmMainElement;
        new (): HTMLKvlmMainElement;
    };
    interface HTMLKvlmNewsletterRegistrationElement extends Components.KvlmNewsletterRegistration, HTMLStencilElement {
    }
    var HTMLKvlmNewsletterRegistrationElement: {
        prototype: HTMLKvlmNewsletterRegistrationElement;
        new (): HTMLKvlmNewsletterRegistrationElement;
    };
    };
    interface HTMLKvlmRootElement extends Components.KvlmRoot, HTMLStencilElement {
    }
    var HTMLKvlmRootElement: {
        prototype: HTMLKvlmRootElement;
        new (): HTMLKvlmRootElement;
    };
    interface HTMLKvlmSubpagesElement extends Components.KvlmSubpages, HTMLStencilElement {
    }
    var HTMLKvlmSubpagesElement: {
        prototype: HTMLKvlmSubpagesElement;
        new (): HTMLKvlmSubpagesElement;
    };
    interface HTMLKvlmTodayElement extends Components.KvlmToday, HTMLStencilElement {
    }
    var HTMLKvlmTodayElement: {
        prototype: HTMLKvlmTodayElement;
        new (): HTMLKvlmTodayElement;
    };
    interface HTMLKvlmUpcomingEventsElement extends Components.KvlmUpcomingEvents, HTMLStencilElement {
    }
    var HTMLKvlmUpcomingEventsElement: {
        prototype: HTMLKvlmUpcomingEventsElement;
        new (): HTMLKvlmUpcomingEventsElement;
    };
    interface HTMLElementTagNameMap {
        "kvlm-authenticate": HTMLKvlmAuthenticateElement;
        "kvlm-background": HTMLKvlmBackgroundElement;
        "kvlm-button": HTMLKvlmButtonElement;
        "kvlm-buttons": HTMLKvlmButtonsElement;
        "kvlm-calendar": HTMLKvlmCalendarElement;
        "kvlm-content": HTMLKvlmContentElement;
        "kvlm-footer": HTMLKvlmFooterElement;
        "kvlm-generic-page": HTMLKvlmGenericPageElement;
        "kvlm-header": HTMLKvlmHeaderElement;
        "kvlm-icon": HTMLKvlmIconElement;
        "kvlm-icon-logo": HTMLKvlmIconLogoElement;
        "kvlm-loader": HTMLKvlmLoaderElement;
        "kvlm-main": HTMLKvlmMainElement;
        "kvlm-newsletter-registration": HTMLKvlmNewsletterRegistrationElement;
        "kvlm-root": HTMLKvlmRootElement;
        "kvlm-subpages": HTMLKvlmSubpagesElement;
        "kvlm-today": HTMLKvlmTodayElement;
        "kvlm-upcoming-events": HTMLKvlmUpcomingEventsElement;
    }
}
declare namespace LocalJSX {
    interface KvlmAuthenticate {
        "at": string;
    }
    interface KvlmBackground {
        "image": string;
        "onLoaded"?: (event: KvlmBackgroundCustomEvent<string>) => void;
        "preview": string;
    }
    interface KvlmButton {
        "block"?: boolean;
        "disabled"?: boolean;
        "download"?: string;
        "forzeBlock"?: boolean;
        "href"?: string;
        "target"?: string;
        "type"?: HTMLButtonElement['type'];
    }
    interface KvlmButtons {
        "direction"?: 'horizontal' | 'vertical';
        "forzeDirection"?: 'horizontal' | 'vertical';
    }
    interface KvlmCalendar {
    }
    interface KvlmContent {
        "visible"?: boolean;
    }
    interface KvlmFooter {
    }
    interface KvlmGenericPage {
        "context": GenericRouteContext;
        "src": string;
    }
    interface KvlmHeader {
    }
    interface KvlmIcon {
    }
    interface KvlmIconLogo {
    }
    interface KvlmLoader {
    }
    interface KvlmMain {
    }
    interface KvlmNewsletterRegistration {
        "at": string;
    }
        "at": string;
    }
    interface KvlmRoot {
    }
    interface KvlmSubpages {
        "src": string;
    }
    interface KvlmToday {
    }
    interface KvlmUpcomingEvents {
        "calendarUrl": string;
        "loading"?: string;
    }
    interface IntrinsicElements {
        "kvlm-authenticate": KvlmAuthenticate;
        "kvlm-background": KvlmBackground;
        "kvlm-button": KvlmButton;
        "kvlm-buttons": KvlmButtons;
        "kvlm-calendar": KvlmCalendar;
        "kvlm-content": KvlmContent;
        "kvlm-footer": KvlmFooter;
        "kvlm-generic-page": KvlmGenericPage;
        "kvlm-header": KvlmHeader;
        "kvlm-icon": KvlmIcon;
        "kvlm-icon-logo": KvlmIconLogo;
        "kvlm-loader": KvlmLoader;
        "kvlm-main": KvlmMain;
        "kvlm-newsletter-registration": KvlmNewsletterRegistration;
        "kvlm-root": KvlmRoot;
        "kvlm-subpages": KvlmSubpages;
        "kvlm-today": KvlmToday;
        "kvlm-upcoming-events": KvlmUpcomingEvents;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "kvlm-authenticate": LocalJSX.KvlmAuthenticate & JSXBase.HTMLAttributes<HTMLKvlmAuthenticateElement>;
            "kvlm-background": LocalJSX.KvlmBackground & JSXBase.HTMLAttributes<HTMLKvlmBackgroundElement>;
            "kvlm-button": LocalJSX.KvlmButton & JSXBase.HTMLAttributes<HTMLKvlmButtonElement>;
            "kvlm-buttons": LocalJSX.KvlmButtons & JSXBase.HTMLAttributes<HTMLKvlmButtonsElement>;
            "kvlm-calendar": LocalJSX.KvlmCalendar & JSXBase.HTMLAttributes<HTMLKvlmCalendarElement>;
            "kvlm-content": LocalJSX.KvlmContent & JSXBase.HTMLAttributes<HTMLKvlmContentElement>;
            "kvlm-footer": LocalJSX.KvlmFooter & JSXBase.HTMLAttributes<HTMLKvlmFooterElement>;
            "kvlm-generic-page": LocalJSX.KvlmGenericPage & JSXBase.HTMLAttributes<HTMLKvlmGenericPageElement>;
            "kvlm-header": LocalJSX.KvlmHeader & JSXBase.HTMLAttributes<HTMLKvlmHeaderElement>;
            "kvlm-icon": LocalJSX.KvlmIcon & JSXBase.HTMLAttributes<HTMLKvlmIconElement>;
            "kvlm-icon-logo": LocalJSX.KvlmIconLogo & JSXBase.HTMLAttributes<HTMLKvlmIconLogoElement>;
            "kvlm-loader": LocalJSX.KvlmLoader & JSXBase.HTMLAttributes<HTMLKvlmLoaderElement>;
            "kvlm-main": LocalJSX.KvlmMain & JSXBase.HTMLAttributes<HTMLKvlmMainElement>;
            "kvlm-newsletter-registration": LocalJSX.KvlmNewsletterRegistration & JSXBase.HTMLAttributes<HTMLKvlmNewsletterRegistrationElement>;
            "kvlm-root": LocalJSX.KvlmRoot & JSXBase.HTMLAttributes<HTMLKvlmRootElement>;
            "kvlm-subpages": LocalJSX.KvlmSubpages & JSXBase.HTMLAttributes<HTMLKvlmSubpagesElement>;
            "kvlm-today": LocalJSX.KvlmToday & JSXBase.HTMLAttributes<HTMLKvlmTodayElement>;
            "kvlm-upcoming-events": LocalJSX.KvlmUpcomingEvents & JSXBase.HTMLAttributes<HTMLKvlmUpcomingEventsElement>;
        }
    }
}
