name: Deploy

on:
  push:
    branches:
      - next
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.9.0
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm -r --parallel lint

      - name: Build
        run: pnpm -r --filter @kvlm/ui... build

      - uses: actions/upload-artifact@v3
        if: success() && github.ref == 'refs/heads/next' && github.event_name != 'pull_request'
        with:
          name: latest
          path: packages/ui/dist

  deploy:
    name: Deploy
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: actions/download-artifact@v4
        with:
          name: latest
          path: packages/ui/dist
      - uses: actions/upload-pages-artifact@v3
        with:
          path: "packages/ui/dist"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
